name: Run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: 1.25.x

      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Run tests
        run: go test

  smoke-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
        with:
          install: true

      - name: Build Docker image and store in cache
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          push: false
          load: true
          tags: exercism/go-representer
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
